force-app/main/default/objects/chargebee__c/chargebee__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>chargebee</label>
</CustomObject>

force-app/main/default/objects/chargebee__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>API Keys are essential when you have to authenticate while trying to connect to Chargebee&#39;s API.

You can find your API keys in the web interface under Settings &gt; API and Webhooks &gt; API Keys</description>
    <inlineHelpText>API Keys are essential when you have to authenticate your session while trying to connect to Chargebee&#39;s API.

You can find your API keys in the web interface under Settings &gt; API and Webhooks &gt; API Keys</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FieldPermissions.cls
@RestResource(urlMapping='/fieldpermissions/*')
global with sharing class FieldPermissions {

    @HttpGet
    global static string doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        //String accountId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        //Account result = [SELECT Id, Name, Phone, Website FROM Account WHERE Id = :accountId];
        chargebee__c mhc = chargebee__c.getInstance();
        string apikey = mhc.API_Key__c;
        return apikey;
    }
    
      
}