force-app/main/default/objects/chargebee__c/chargebee__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>chargebee</label>
</CustomObject>

force-app/main/default/objects/chargebee__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>API Keys are essential when you have to authenticate while trying to connect to Chargebee&#39;s API.

You can find your API keys in the web interface under Settings &gt; API and Webhooks &gt; API Keys</description>
    <inlineHelpText>API Keys are essential when you have to authenticate your session while trying to connect to Chargebee&#39;s API.

You can find your API keys in the web interface under Settings &gt; API and Webhooks &gt; API Keys</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/chargebee__c/fields/ChargeBee_URL__c.field-meta.xml
<CustomField>
    <fullName>ChargeBee_URL__c</fullName>
    <description>The portal url for chargebee</description>
    <label>ChargeBee URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/chargebee__c/fields/Settings_JSON__c.field-meta.xml
<CustomField>
    <fullName>Settings_JSON__c</fullName>
    <description>All chargebee site settings and configurations in JSON</description>
    <label>Settings JSON</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/chargebee__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <description>Chargebee Username</description>
    <inlineHelpText>Chargebee Username</inlineHelpText>
    <label>User Name</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/RetrieveSettings.cls
@RestResource(urlMapping='/retrieve/v1_5/*')
global with sharing class RetrieveSettings {

    @HttpGet
    global static string doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        chargebee__c mhc = chargebee__c.getInstance();
        string url = mhc.ChargeBee_URL__c;
        string apikey = mhc.API_Key__c;
        string json = mhc.Settings_JSON__c;
        string name = mhc.User_Name__c;
        string settings = url+'|'+apikey+'|'+name+'|'+json;
        return settings;
    }
    
    
}