force-app/main/default/objects/chargebee__c/chargebee__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>chargebee</label>
</CustomObject>

force-app/main/default/objects/chargebee__c/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>API Keys are essential when you have to authenticate while trying to connect to Chargebee&#39;s API.

You can find your API keys in the web interface under Settings &gt; API and Webhooks &gt; API Keys</description>
    <inlineHelpText>API Keys are essential when you have to authenticate your session while trying to connect to Chargebee&#39;s API.

You can find your API keys in the web interface under Settings &gt; API and Webhooks &gt; API Keys</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/chargebee__c/fields/ChargeBee_URL__c.field-meta.xml
<CustomField>
    <fullName>ChargeBee_URL__c</fullName>
    <description>The portal url for chargebee</description>
    <label>ChargeBee URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/chargebee__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <description>Chargebee Username</description>
    <inlineHelpText>Chargebee Username</inlineHelpText>
    <label>User Name</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/ChargeBeeSettings.cls
@RestResource(urlMapping='/chargebeesettings/*')
global with sharing class ChargeBeeSettings {

    @HttpGet
    global static string doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
      //  String accountId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
       // Account result = [SELECT Id, Name, Phone, Website FROM Account WHERE Id = :accountId];
        chargebee__c mhc = chargebee__c.getInstance();

        string apikey = mhc.API_Key__c;

        return apikey;
    }

    @HttpPost
    global static String doPost(string apikey,string username,string chargebeeurl) {
    chargebee__c mhc = chargebee__c.getInstance();
    if(apikey!=null)
    {
      mhc.API_Key__c=apikey;
    }
    if(username!=null)
    {
      mhc.User_Name__c=username;
    }
    if(chargebeeurl!=null)
    {
      mhc.ChargeBee_URL__c=chargebeeurl;
    }
    upsert mhc;
    return mhc.API_Key__c;
    }
}